name: lightning
channels:
  - bioconda
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=py312haa95532_0
  - aiohappyeyeballs=2.4.4=py312haa95532_0
  - aiohttp=3.11.10=py312h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - alembic=1.13.3=py312haa95532_0
  - amply=0.1.6=py312haa95532_1
  - annotated-types=0.6.0=py312haa95532_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=h57928b3_42_cpu
  - attrs=24.3.0=py312haa95532_0
  - aws-c-auth=0.7.4=h38fcb40_4
  - aws-c-cal=0.6.6=hd5965a7_0
  - aws-c-common=0.9.3=hcfcfb64_0
  - aws-c-compression=0.2.17=hd5965a7_3
  - aws-c-event-stream=0.3.2=h97c4253_3
  - aws-c-http=0.7.13=heb5e3ba_5
  - aws-c-io=0.13.35=h9064048_1
  - aws-c-mqtt=0.9.7=h993aabb_1
  - aws-c-s3=0.3.18=h510fa76_2
  - aws-c-sdkutils=0.1.12=hd5965a7_2
  - aws-checksums=0.1.17=hd5965a7_2
  - aws-crt-cpp=0.24.3=hd326782_3
  - aws-sdk-cpp=1.11.156=hc1d519e_5
  - babel=2.16.0=pyhd8ed1ab_1
  - bcrypt=3.2.0=py312h827c3e9_2
  - blas=1.0=mkl
  - blinker=1.6.2=py312haa95532_0
  - bokeh=3.6.2=py312haa95532_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.4.2=py312h4b0e54e_0
  - brotli=1.0.9=ha925a31_2
  - brotli-python=1.1.0=py312h275cf98_2
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2025.7.15=haa95532_0
  - cachetools=5.3.3=py312haa95532_0
  - cairo=1.16.0=hc68a040_5
  - cartopy=0.24.0=py312h72972c8_0
  - certifi=2025.8.3=py312haa95532_0
  - cffi=1.17.1=py312h4389bb4_0
  - cftime=1.6.4=py312h827c3e9_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_1
  - click=8.1.7=py312haa95532_0
  - cloudpickle=3.0.0=py312haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=py312haa95532_2
  - colorlog=5.0.1=py312haa95532_1
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_1
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.3.1=py312h214f63a_0
  - crc32c=2.7.1=py312h4389bb4_0
  - cryptography=43.0.3=py312hbd6ee87_1
  - cuda-cccl=12.6.77=0
  - cuda-cccl_win-64=12.6.77=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-opencl-dev=12.6.77=0
  - cuda-profiler-api=12.6.77=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=1.0.1=py312h827c3e9_0
  - dask=2024.5.0=py312haa95532_0
  - dask-core=2024.5.0=py312haa95532_0
  - dask-expr=1.1.0=py312haa95532_0
  - databricks-sdk=0.33.0=py312haa95532_0
  - datrie=0.8.2=py312h2bbff1b_0
  - deprecated=1.2.13=py312haa95532_0
  - distributed=2024.5.0=py312haa95532_0
  - docker-py=7.1.0=py312haa95532_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - dpath=2.2.0=pyha770c72_0
  - eido=0.2.4=pyhd8ed1ab_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - expat=2.7.1=h8ddb27b_0
  - fast-histogram=0.14=py312h1a27103_3
  - filelock=3.16.1=pyhd8ed1ab_1
  - flask=3.0.3=py312haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hb33846d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py312h2bbff1b_0
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozenlist=1.5.0=py312h827c3e9_0
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - geos=3.13.1=h9ea8674_0
  - getopt-win32=0.1=h2bbff1b_0
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py312haa95532_0
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - glpk=4.65=h2bbff1b_3
  - google-auth=2.29.0=py312haa95532_0
  - graphene=1.4=py_0
  - graphite2=1.3.14=hd77b12b_1
  - graphql-core=1.1=py_1
  - graphql-relay=0.4.5=py_1
  - graphviz=12.2.1=hfae31f5_2
  - greenlet=3.1.1=py312h5da7b33_0
  - grpcio=1.58.1=py312h7894644_0
  - gts=0.7.6=h63ab5a1_3
  - h2=4.1.0=pyhd8ed1ab_1
  - h5netcdf=1.2.0=py312haa95532_0
  - h5py=3.12.1=py312h535c9fb_1
  - harfbuzz=4.3.0=hb646838_2
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.14.5=h44af213_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - hpack=4.0.0=pyhd8ed1ab_1
  - humanfriendly=10.0=py312haa95532_1
  - hydra-colorlog=1.2.0=pyhd8ed1ab_2
  - hydra-core=1.3.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - immutables=0.21=py312h4389bb4_0
  - importlib-metadata=8.5.0=py312haa95532_0
  - importlib_resources=6.4.0=py312haa95532_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2025.0.0=h57928b3_1164
  - itsdangerous=2.2.0=py312haa95532_0
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=py312haa95532_0
  - jpeg=9e=h827c3e9_3
  - jsonschema=4.23.0=py312haa95532_0
  - jsonschema-specifications=2023.7.1=py312haa95532_0
  - jupyter_core=5.7.2=py312haa95532_0
  - keras=3.9.2=pyh753f3f9_0
  - kiwisolver=1.4.4=py312hd77b12b_0
  - lcms2=2.16=hb4a4139_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20230802.1=cxx17_h63175ca_0
  - libarrow=11.0.0=hdd83e72_42_cpu
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcrc32c=1.1.2=hd77b12b_0
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.7.77=0
  - libcurl=8.11.1=haff574d_0
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libdeflate=1.22=h5bf469e_0
  - libevent=2.1.12=h56d1f94_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.2=h8ffe710_5
  - libgcc=14.2.0=h1383e82_1
  - libgd=2.3.3=ha43c60c_1
  - libglib=2.78.4=ha17d25a_0
  - libgomp=14.2.0=h1383e82_1
  - libgoogle-cloud=2.12.0=ha74b051_3
  - libgrpc=1.58.1=h43eea02_0
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.17=hcfcfb64_2
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblzma=5.6.3=h2466b09_1
  - libnetcdf=4.8.1=h99c5407_5
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=12.6.77=0
  - libnvfatbin-dev=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=4.24.3=hb8276f3_1
  - libsqlite=3.47.2=h67fdade_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.19.0=ha2b3283_1
  - libtiff=4.5.1=h44ae7cf_1
  - libutf8proc=2.8.0=hb602f4b_1
  - libuv=1.49.2=h2466b09_0
  - libwebp=1.5.0=h3b0e114_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_8
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.5=h24da03e_0
  - libzip=1.8.0=h289538f_1
  - libzlib=1.2.13=h2466b09_6
  - lightning=2.5.0.post0=pyhd8ed1ab_0
  - lightning-utilities=0.11.9=pyhd8ed1ab_1
  - locket=1.0.0=py312haa95532_0
  - logmuse=0.2.8=pyhd8ed1ab_1
  - lz4=4.3.2=py312h827c3e9_1
  - lz4-c=1.9.4=h2bbff1b_1
  - mako=1.2.3=py312haa95532_0
  - markdown=3.4.1=py312haa95532_0
  - markdown-it-py=2.2.0=py312haa95532_1
  - markupsafe=3.0.2=py312h31fea79_1
  - matplotlib-base=3.10.0=py312he19b0ae_0
  - mdurl=0.1.0=py312haa95532_0
  - mkl=2023.1.0=h6a75c08_48682
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - ml_dtypes=0.5.1=py312h72972c8_0
  - mpl-scatter-density=0.8=pyhd8ed1ab_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py312hd5eb7cc_0
  - multidict=6.1.0=py312h827c3e9_0
  - namex=0.0.9=pyhd8ed1ab_0
  - nbformat=5.10.4=py312haa95532_0
  - netcdf4=1.6.2=py312had6fc2f_0
  - networkx=3.4.2=pyh267e887_2
  - numcodecs=0.15.0=py312h72972c8_0
  - numexpr=2.10.1=py312h4cd664f_0
  - numpy=1.26.4=py312hfd52020_0
  - numpy-base=1.26.4=py312h4dde369_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.5.0=ha4e3fda_1
  - opentelemetry-api=1.29.0=pyhd8ed1ab_1
  - opentelemetry-sdk=1.29.0=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.50b0=pyh3cfb1c2_0
  - optree=0.15.0=py312hd5eb7cc_0
  - orc=1.9.0=hd95f75e_3
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312h5da7b33_0
  - pango=1.50.7=h78c2152_0
  - paramiko=3.5.0=py312haa95532_0
  - partd=1.4.2=py312haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.7=pyhd8ed1ab_2
  - pillow=11.0.0=py312h096bfcc_1
  - pip=24.3.1=pyh8b19718_2
  - pixman=0.40.0=h2bbff1b_1
  - plac=1.3.4=pyhd3eb1b0_0
  - platformdirs=3.10.0=py312haa95532_0
  - pluggy=1.5.0=py312haa95532_0
  - poppler=24.09.0=h6558a74_1
  - poppler-data=0.4.11=haa95532_1
  - proj=9.3.1=ha107b6e_0
  - promise=2.3=py312haa95532_0
  - propcache=0.2.0=py312h827c3e9_0
  - protobuf=4.24.3=py312hd11f8d2_1
  - psutil=5.9.0=py312h2bbff1b_0
  - pthread-stubs=0.4=h0e40799_1002
  - pulp=2.8.0=py312h2e8e312_0
  - pyarrow=11.0.0=py312had8a6e9_2
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.10.3=py312haa95532_0
  - pydantic-core=2.27.1=py312h636fa0f_0
  - pygments=2.18.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py312h7edc060_1
  - pyopenssl=24.2.1=py312haa95532_0
  - pyparsing=3.2.0=py312haa95532_0
  - pyproj=3.6.1=py312hc725b1e_5
  - pyreadline3=3.4.1=py312haa95532_0
  - pyshp=2.3.1=pyhd8ed1ab_1
  - pysocks=1.7.1=pyh09c184e_7
  - pytest=7.4.4=py312haa95532_0
  - python=3.12.3=h2628c8c_0_cpython
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.20.0=py312haa95532_0
  - python-graphviz=0.20.3=pyh91182bf_2
  - python-lmdb=1.6.2=py312h5da7b33_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=5_cp312
  - pytorch=2.4.1=py3.12_cuda12.4_cudnn9_0
  - pytorch-cuda=12.4=h3fd98bf_7
  - pytorch-lightning=2.5.0.post0=pyh101cb37_0
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312haa95532_0
  - pywin32=305=py312h2bbff1b_0
  - pyyaml=6.0.2=py312h4389bb4_1
  - re2=2023.03.02=hd4eee63_0
  - referencing=0.30.2=py312haa95532_0
  - requests=2.32.3=pyhd8ed1ab_1
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=13.9.4=py312haa95532_0
  - rpds-py=0.10.6=py312h636fa0f_1
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.5.2=py312h585ebfc_0
  - scipy=1.14.1=py312h9d85e7c_0
  - sentry-sdk=2.18.0=py312haa95532_0
  - setproctitle=1.2.2=py312h827c3e9_1
  - setuptools=75.6.0=pyhff2d567_1
  - shapely=2.1.0=py312h3f81574_0
  - shellingham=1.5.0=py312haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - slack-sdk=3.34.0=pyhd8ed1ab_0
  - slack_sdk=3.34.0=hd8ed1ab_0
  - smart_open=5.2.1=py312haa95532_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snakemake=9.10.1=hdfd78af_0
  - snakemake-interface-common=1.21.0=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.3.3=pyhdfd78af_0
  - snakemake-interface-logger-plugins=1.2.3=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.1.0=pyhdfd78af_0
  - snakemake-interface-scheduler-plugins=2.0.0=pyhdfd78af_0
  - snakemake-interface-storage-plugins=4.2.1=pyhdfd78af_0
  - snakemake-minimal=9.10.1=pyhdfd78af_0
  - snappy=1.1.10=h6c2663c_1
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - sqlalchemy=2.0.37=py312h54f65d0_0
  - sqlite=3.47.2=h2466b09_0
  - sqlparse=0.5.2=py312haa95532_0
  - sympy=1.13.3=pyh04b8f61_4
  - tabulate=0.9.0=py312haa95532_0
  - tbb=2021.13.0=h62715c5_1
  - tblib=1.7.0=pyhd3eb1b0_0
  - tensorboard=2.17.0=py312haa95532_0
  - tensorboard-data-server=0.7.0=py312haa95532_1
  - threadpoolctl=3.5.0=py312hfc267ef_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=py312haa95532_0
  - torchmetrics=1.6.1=pyhd8ed1ab_0
  - tornado=6.4.2=py312h827c3e9_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=py312haa95532_0
  - typer=0.9.0=py312haa95532_0
  - typing=3.10.0.0=py312haa95532_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2024b=hc8b5060_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=15.1.0=py312h827c3e9_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - vc=14.40=haa95532_2
  - vc14_runtime=14.44.35208=h4927774_10
  - veracitools=0.1.3=py_0
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - waitress=3.0.2=py312haa95532_0
  - wandb=0.21.1=py312hb0142fd_0
  - websocket-client=1.8.0=py312haa95532_0
  - werkzeug=3.0.6=py312haa95532_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.0=py312h4389bb4_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xyzservices=2022.9.0=py312haa95532_1
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.18.0=py312h827c3e9_0
  - yte=1.5.5=pyha770c72_0
  - zict=3.0.0=py312haa95532_0
  - zipp=3.21.0=py312haa95532_0
  - zlib=1.2.13=h2466b09_6
  - zstandard=0.23.0=py312h7606c53_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - anyio==4.9.0
      - fastapi==0.115.12
      - fstd2nc==0.20240625.7
      - fstd2nc-deps==0.20200304.6
      - h11==0.16.0
      - meson==1.8.0
      - mlflow==2.22.0
      - mlflow-skinny==2.22.0
      - ninja==1.11.1.4
      - pyasynchat==1.0.4
      - pyasyncore==1.0.4
      - python-magic-bin==0.4.14
      - sniffio==1.3.1
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-jquery==4.1
      - starlette==0.46.2
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - uvicorn==0.34.2
      - xarray==2025.1.2
      - zarr==3.0.4