model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.checkpoint_dir}  # directory to save the model file
  filename: model  # checkpoint filename
  monitor: "valid_loss"  # name of the logged metric which determines when model is improving
  save_top_k: True
  mode: "min"
  save_weights_only: False  # if True, then only the modelâ€™s weights will be saved
  every_n_train_steps: null  # number of training steps between checkpoints
  train_time_interval: null  # checkpoints are monitored at the specified time interval
  every_n_epochs: null  # number of epochs between checkpoints
  save_on_train_epoch_end: null  # whether to run checkpointing at the end of the training epoch or the end of validation
