# Statistics of the dataset
statistics:
  # Statistics of the training set
  data:
    # Function
    _target_: inverse.data.statistics.compute_statistics
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Variables
      vars:
        prof:
          load:
            _target: ${data.stage[0].vars.prof.load._target_}
            path: ${data.stage[0].vars.prof.load.path}
            split: null
        surf:
          load:
            _target: ${data.stage[0].vars.surf.load._target_}
            path: ${data.stage[0].vars.surf.load.path}
            split: null
        meta:
          load:
            _target: ${data.stage[0].vars.meta.load._target_}
            path: ${data.stage[0].vars.meta.load.path}
            split: null
        hofx:
          load:
            _target: ${data.stage[0].vars.hofx.load._target_}
            path: ${data.stage[0].vars.hofx.load.path}
            split: null
        lat:
          load:
            _target: ${data.stage[0].vars.lat.load._target_}
            path: ${data.stage[0].vars.lat.load.path}
        lon:
          load:
            _target: ${data.stage[0].vars.lon.load._target_}
            path: ${data.stage[0].vars.lon.load.path}
        scans:
          load:
            _target: ${data.stage[0].vars.scans.load._target_}
            path: ${data.stage[0].vars.scans.load.path}
        pressure:
          load:
            _target: ${data.stage[0].vars.pressure.load._target_}
            path: ${data.stage[0].vars.pressure.load.path}
      # Cloud filter: Consider only cloudy data, if not null (None)
      cloud_filter:
        load:
          _target: ${data.stage[0].vars.cloud_filter.load._target_}
          prof: ${preparation.statistics.data.input.vars.prof.load}
    # What the method produces as output (pickle file)
    output:
      path: ${paths.data_dir}/normalization/stats_cloud_filter.pkl