# Note: The order of defaults determines the order in which configs override each other.
defaults:
  - hydra: default
  - paths: default
  - data: inverse_
  - preparation: inverse_default
  - loader: inverse_train  # Training only
  - model: inverse_operator
  - trainer: default
  - callbacks: inverse_default
  - logger: default
  - _self_
