# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: "."

# Run name, used to identify the run
run_id: "run"

# Path to data directory
data_dir: "../../GOES_ML-main/Data"

# Task directory; where to store outputs
# TODO: Fix this
task_dir: "../inverse_outputs"

# Path to logging directory
log_dir: ${hydra:runtime.output_dir}/logs

# Path to checkpoints
checkpoint_dir: ${hydra:runtime.output_dir}/checkpoints/${paths.run_id}

# Path to runs (inferences)
run_dir: ${hydra:runtime.output_dir}/runs/${paths.run_id}

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}