# Data loader configuration for forward model training
_target_: forward.model.data_loader.Dataloader
_recursive_: false
batch_size: 32  # Batch size for training
# TODO: Due to Windows limitations, num_workers must be set to 0. Change this to a higher value for Linux/MacOS for better performance.
num_workers: 0  # Number of workers for data loading
# TODO: Set persistent_workers to true if num_workers > 0 for better performance.
persistent_workers: false  # Keep workers alive between epochs

# Split the data into training, validation, and test sets
stage:
  # Training set
  train:
    # Dataset class
    _target_: forward.model.data_loader.CRTMDataset
    _recursive_: false
    # Variables to use as input
    input:
      prof: ${data.stage.train.vars.prof}
      surf: ${data.stage.train.vars.surf}
      meta: ${data.stage.train.vars.meta}
      cloud_filter: ${data.stage.train.vars.cloud_filter}
    # Variables to use as targets
    target:
      hofx: ${data.stage.train.vars.hofx}
  # Validation set
  valid:
    # Dataset class
    _target_: forward.model.data_loader.CRTMDataset
    _recursive_: false
    # Variables to use as input
    input:
      prof: ${data.stage.valid.vars.prof}
      surf: ${data.stage.valid.vars.surf}
      meta: ${data.stage.valid.vars.meta}
      cloud_filter: ${data.stage.valid.vars.cloud_filter}
    # Variables to use as targets
    target:
      hofx: ${data.stage.valid.vars.hofx}
  # Test set
  test:
    # Dataset class
    _target_: forward.model.data_loader.CRTMDataset
    _recursive_: false
    # Variables to use as input
    input:
      prof: ${data.stage.test.vars.prof}
      surf: ${data.stage.test.vars.surf}
      meta: ${data.stage.test.vars.meta}
      cloud_filter: ${data.stage.test.vars.cloud_filter}
    # Variables to use as targets
    target:
      hofx: ${data.stage.test.vars.hofx}
    # Results
    results:
      # Forward model simulations
      hofx:
        # Path
        path: ${paths.run_dir}/test_hofx.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${loader.stage.test.results.hofx.path}
        # Load function
        load:
          _target_: utilities.io.load_npy
          path: ${loader.stage.test.results.hofx.path}
  # Prediction set
  predict:
    # Dataset class
    _target_: forward.model.data_loader.CRTMDataset
    _recursive_: false
    # Variables to use as input
    input:
      prof: ${data.stage.predict.vars.prof}
      surf: ${data.stage.predict.vars.surf}
      meta: ${data.stage.predict.vars.meta}
    # Results
    results:
      # Forward model simulations
      hofx:
        # Path
        path: ${paths.run_dir}/predict_hofx.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${loader.stage.predict.results.hofx.path}
        # Load function
        load:
          _target_: utilities.io.load_npy
          path: ${loader.stage.predict.results.hofx.path}